### ISSUE TITLE
 wget URL is missing 'raw' link; downloads the HTML wrapper page

### ISSUE THREAD

**Issue by danbri** [samjabrahams/tensorflow-on-raspberry-pi#1]
For me at least, I needed:

     wget https://github.com/samjabrahams/tensorflow-on-raspberry-pi/raw/master/bin/tensorflow-0.7.1-cp27-none-linux_armv7l.whl

**Comment by samjabrahams** [comment]
You're right! I didn't actually attempt to install the "wheel" after I ran that command, so I missed this. Patching in shortly.

**Comment by samjabrahams** [comment]
Patched.
