### ISSUE TITLE
pip install 

### ISSUE THREAD

**Issue by jmlb** [samjabrahams/tensorflow-on-raspberry-pi#10]
Hi,
I want to install tensorflow package on raspberry pi.
I was able to go through the first step: download of the package. But when trying to pip install it, I get the following error lines:

> could not find any downloads that satisfy the requirements...
> cleaning up ...
> No distributions at all found for tensorflow-0.8.0rc0...
> I tried both install with pip and pip2 without success.
> Has anyone been facing that error, and was able to solve it?
> Thanks.

JM

**Comment by samjabrahams** [comment]
Thanks for opening this up- I'm currently flashing an SD card from scratch so I can try to replicate this bug. Hopefully will get back to you soon!

**Comment by StryxZilla** [comment]
I am stuck here as well, so any help is appreciated.

**Comment by samjabrahams** [comment]
Hi @jmlb and @StryxZilla : 

Sorry for the delay- I had to toss a bad SD card in order to get going.

I'm not able to duplicate the issues you're having. I went through it copying and pasting the command-line instructions directly into the console. It sounds like the the file either isn't getting downloaded properly, or the file is located in a different directory than where you are trying to install it.

Can you provide more details about exactly what commands you ran, and what the output you saw was?

**Comment by StryxZilla** [comment]
@samjabrahams Yeah, I know the file was downloaded, but I will double check the directory.  If those seem in order I will try to see what other details I can get (possibly a quick vid).

**Comment by StryxZilla** [comment]
![capture](https://cloud.githubusercontent.com/assets/17952317/15058174/69403ae6-12e0-11e6-8d0f-8fc1f706a5ad.JPG)

@samjabrahams  That is what I am seeing.

**Comment by samjabrahams** [comment]
Fascinating- it's determined to try and download it from PyPi instead of looking locally. Perhaps try something like this:

```
sudo pip install ./tensorflow-0.8.0-cp27-none-linux_armv7l.whl
```

I'll see what else I can find.

**Comment by samjabrahams** [comment]
I think I see what's going on. Double check your download URL- if you look at the `wget` output, you'll see that it didn't actually download anything. My guess is that if you run `ls -la`, the .whl file you have is actually 0 bytes.

To be specific, here's what you entered for `wget`:

```
wget https://github.com/samjabrahams/tensorflow-on-raspberry-pi/bin/tensorflow-0.8.0-cp27-none-linux_armv7l.whl
```

Here's what it should be:

```
wget https://github.com/samjabrahams/tensorflow-on-raspberry-pi/raw/master/bin/tensorflow-0.8.0-cp27-none-linux_armv7l.whl
```

**Comment by StryxZilla** [comment]
Yeah.  I'll check size, but I just went and saved via browser before I realized my typo.  So, it's likely just me not giving you all the info there.

**Comment by samjabrahams** [comment]
Maybe try adding `./` before the .whl file name to indicate that you're looking in the current directory:

```
sudo pip install ./tensorflow-0.8.0-cp27-none-linux_armv7l.whl
```

**Comment by StryxZilla** [comment]
1.  Verified size.  It's good.
2.  I get this when I try to add directory
![image](https://cloud.githubusercontent.com/assets/17952317/15059289/4781fdd4-12e7-11e6-9aa5-2df16001fea9.png)

**Comment by samjabrahams** [comment]
Could you upload the file from the raspberry pi to this comment thread? I really want to try to replicate this.

**Comment by samjabrahams** [comment]
Should be able to drag and drop it into a comment.

**Comment by StryxZilla** [comment]
file:///home/pi/tensorflow-0.8.0-cp27-none-linux_armv7l.whl

There ya go.

**Comment by StryxZilla** [comment]
Hmm doesn't look like it uploaded.  Wonder if it is due to size.  I will screw with it later.

**Comment by StryxZilla** [comment]
@samjabrahams  I couldn't get the file uploaded.  I am assuming it is some sort of file size restrictions.  I put it here instead: https://github.com/StryxZilla/noob/blob/master/tensorflow-0.8.0-cp27-none-linux_armv7l.whl.  Does that work?

**Comment by samjabrahams** [comment]
@StryxZilla - just wanted to let you know that I haven't forgotten about this. I haven't had time to sit down and take a longer look at this, but I'll hopefully get to in in the next day or two. Thanks for the effort in getting the binary online!

**Comment by samjabrahams** [comment]
Hey @StryxZilla - I'm closing this out for now; I wasn't able to figure out why the file wouldn't pip install properly, but you might have more luck with the newer releases!

**Comment by Tomires** [comment]
Just in case someone is still wondering about how to fix this issue, try running _sudo pip install --upgrade pip_ . My raspbian installation included a particularly ancient version of pip in its repos.
