### ISSUE TITLE
OMG,The Raspberry Pi 3ModelB will reboot when i run 'python Classify_image.py'

### ISSUE THREAD

**Issue by bnhc** [samjabrahams/tensorflow-on-raspberry-pi#106]
### Describe the Issue
       The Raspberry Pi 3 Model B will reboot when i run the programer.And I don't know the question.I have check the log (/var/log).I need your help .Thank you .
### Hardware/Software Info
     Hardware: Paspberry Pi 3 Model B
     Software Info: Raspbian GNU/Linux 8 \n \l
     Python Version : 2.7.9
Please provide the following information about your Raspberry Pi setup:

* Raspberry Pi model: 3 Model B
* Operating System used: Raspbian GNU/Linux 8 \n \l
* Version of Python used: 2.7.9
* SD card memory size: 8G
* Size of USB/other device used as swap (if building from source): 
* TensorFlow git commit hash (if building from source): 

### Relevant Console Output/Logs
 I can' find the error log . But i check the programer file.
 when the file run as this :
def create_graph():
  with tf.gfile.FastGFile(os.path.join(FLAGS.model_dir,'classify_image_graph_def.pb'),'rb') as f:
      graph_def =tf.GraphDef()
      graph_def.ParseFromString（f.read()）
      _  = tf.import_graph_def(graph_def,name='')

**Comment by bnhc** [comment]
Maybe WatchDog?

**Comment by EddieOne** [comment]
Could be power cable, it's 2.5 amps?

**Comment by bnhc** [comment]
This is not the raspberry hardward or Other things's problem. One day ,I find the raspberry will restart before the network interface offline.So I repaire the Network interface.And it works.After run the 
test  programer and image , I get the result.  
     In other word,I  still don't  understand this problem .But it works well .

**Comment by bnhc** [comment]
This is not the raspberry hardward or Other things's problem. One day ,I find the raspberry will restart before the network interface offline.So I repaire the Network interface and it works.After run the test programer and image , I get the result. Well done! 
      In other word,I still don't understand this problem .But it works well .
