### ISSUE TITLE
mvn

### ISSUE THREAD

**Issue by TaylorHere** [samjabrahams/tensorflow-on-raspberry-pi#11]
when I run this code 'mvn package' it show Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile (default-testCompile) on project protobuf-java: Compilation failure

**Comment by TaylorHere** [comment]
I'm trying to build on raspberry pi 2 a with Linux raspberrypi 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux

**Comment by samjabrahams** [comment]
Thanks for opening this up. I'll take a look to see if I can replicate the issue, though unfortunately I can't devote too much time to this. Sadly, I don't have the resources to sort through disparities in build processes between the RPi2 and RPi3.

**Comment by neuralearner** [comment]
Hello, I'm experiencing the same issue but on a raspberry pi 3 running Raspbian 8.0

**Comment by samjabrahams** [comment]
Interesting. I've never seen this error before. It may have something to do with the version of Java being used?

**Comment by jtoy** [comment]
I have this too.

**Comment by samjabrahams** [comment]
The `mvn` instruction is no longer needed in order to build TensorFlow, so this issue should be fixed moving forward.
