### ISSUE TITLE
Question on GPU

### ISSUE THREAD

**Issue by Mouss94** [samjabrahams/tensorflow-on-raspberry-pi#15]
Hello , First thank you for this great project !
I would like to know please if tensorflow use the GPu on the raspberry pi ? 
Thanks you

**Comment by samjabrahams** [comment]
Thanks for the question- unfortunately, at this time TensorFlow isn't compatible with the GPU on the Raspberry Pi, as TensorFlow only supports NVIDIA CUDA graphics cards. 

One day (hopefully), a group of people will find a reasonable way to map OpenCL/CUDA calls onto the RPi GPU!

In the meantime, if you'd like to create custom deep learning code for the Raspberry Pi's GPU, a good place to get started is [this post by Pete Warden](https://petewarden.com/2014/08/07/how-to-optimize-raspberry-pi-code-using-its-gpu/).

**Comment by danbri** [comment]
Presumably XLA is part of the answer.

https://twitter.com/danbri/status/839431030201266177 -> https://developers.googleblog.com/2017/03/xla-tensorflow-compiled.html

>  XLA (Accelerated Linear Algebra), a compiler for TensorFlow. XLA uses JIT compilation techniques to analyze the TensorFlow graph created by the user at runtime, specialize it for the actual runtime dimensions and types, fuse multiple ops together and emit efficient native machine code for them - for devices like CPUs, GPUs and custom accelerators (e.g. Google’s TPU).

-> https://www.tensorflow.org/performance/xla/

**Comment by samjabrahams** [comment]
That's a pretty fun idea! I can imagine it being a good exercise, and useful if it's implemented correctly. For me personally, it'll have to be a back-burner idea, but I'll leave some links that might be useful moving forward with that idea:

* [Mirror of the official Videocore IV architecture reference guide](https://archive.org/details/pdfy-rXdEJ1TyaZLR_L12)
* [Unofficial Broadcom Videocore IV documentation and samples](https://github.com/hermanhermitage/videocoreiv)
    * [The programmers guide from that repo](https://github.com/hermanhermitage/videocoreiv/wiki/VideoCore-IV-Programmers-Manual)
* [More unofficial samples and documentation](https://github.com/hermanhermitage/videocoreiv-qpu)
* [Implementation of GEMM matrix multiplication on RPI](https://github.com/jetpacapp/pi-gemm)
* [Assembler/disassembler for the RPi QPU](https://github.com/jetpacapp/qpu-asm) 
* [First of blog posts by Pete Warden on deep learning on RPI](https://petewarden.com/2014/06/09/deep-learning-on-the-raspberry-pi/)
* [Second (and lengthier) post by Pete Warden](https://petewarden.com/2014/08/07/how-to-optimize-raspberry-pi-code-using-its-gpu/)

I'll reopen this thread to increase discoverability.

**Comment by arunmrao** [comment]
Hate to see Nvidia having a monopoly on TF GPU - would like explore helping break that - any links, resources appreciated

**Comment by bafu** [comment]
@samjabrahams [py-videocore](https://github.com/nineties/py-videocore) is also an interesting RPi GPGPU library supporting Python.
