### ISSUE TITLE
Installing on a Pi3

### ISSUE THREAD

**Issue by jfperez** [samjabrahams/tensorflow-on-raspberry-pi#2]
Very exciting development but I am running Jessie v8.0 wheel file downloads OK and have dependencies installed but on pip install get the 'not a supported wheel on this platform' message.  see attached file.  Any ideas?

[tensorflow.txt](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/files/183281/tensorflow.txt)

**Comment by samjabrahams** [comment]
Thanks for posting this- could you run this command and quickly let me know what it says?

```
pip --version
```

Most of the time I've seen errors like that in other projects, it's a bug related to using Python 3 instead of Python 2 or vice versa.

**Comment by jfperez** [comment]
Hi Sam

Amazing response time!!!

pip –version produces

pip 8.1.0 from /usr/local/lib/python3.5/site-packages (python 3.5)

John

**Comment by samjabrahams** [comment]
That would appear to be the culprit! Because the wheel is built in Python 2.7, it won't allow you to install using Python 3. Luckily, there should be a pretty easy solution. Try this command, and let me know if it works:

```
sudo pip2 install tensorflow-0.7.1-cp27-none-linux_armv7l.whl
```

**Comment by jfperez** [comment]
That did it!  Successfully installed and I fired up python2.7 and imported tensorflow.  thanks much.  now to start playing.... thanks for all your work on this.  John

**Comment by samjabrahams** [comment]
No problem- thanks for posting this. I'll make a note about this issue in the installation section of the README.
