### ISSUE TITLE
Pip Install "File is not a zip file"

### ISSUE THREAD

**Issue by david-niggli** [samjabrahams/tensorflow-on-raspberry-pi#24]
Hello
First of, thank you for the effort to get tensorflow working on the raspberry pi

The issue:
I followed your step by step instructions for "installing from pip" in the readme
https://github.com/samjabrahams/tensorflow-on-raspberry-pi/raw/master/bin/tensorflow-0.8.0-cp34-cp34m-linux_armv7l.whl
gave me an error 404 url not found, so I replaced it with
https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/bin/tensorflow-0.9.0rc0-py3-none-any.whl

unfortunately i get the following errors:

Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python3/dist-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 640, in unpack_file
    unzip_file(filename, location, flatten=not filename.endswith(('.pybundle', '.whl')))
  File "/usr/lib/python3/dist-packages/pip/util.py", line 510, in unzip_file
    zip = zipfile.ZipFile(zipfp)
  File "/usr/lib/python3.4/zipfile.py", line 937, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.4/zipfile.py", line 978, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

I have googled a bit and tried out some "solutions" but they didn't work

Steps to Reproduce:
Well I really just followed the instructions... changing the url...

Hardware/Software Info:
* Raspberry Pi model:
cat /proc/cpuinfo
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7
Hardware	: BCM2708
Revision	: 000e
Serial		: 0000000027cdfb9a

* Operating System used: Raspbian
* Version of Python used:  python 3.4
* SD card memory size: 16 GB (new SD card and freshly installed os)

**Comment by samjabrahams** [comment]
Whoops! Thanks for the heads up- looks like I forgot to update the download link. I'll check out the Python 3 wheel to see if I can replicate the install error.

**Comment by samjabrahams** [comment]
I see the issue- replace the word "blob" with the word "raw" in your URL. So instead of this:

https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/bin/tensorflow-0.9.0rc0-py3-none-any.whl

Try this:

https://github.com/samjabrahams/tensorflow-on-raspberry-pi/raw/master/bin/tensorflow-0.9.0rc0-py3-none-any.whl

I'm fixing the GUIDE and README now, I'll close this once I do that and hear back from you.

**Comment by david-niggli** [comment]
ok I'm on it

**Comment by samjabrahams** [comment]
Glad it worked for you! I happened to be in a good spot to help when I saw the issue, so the timing worked out nicely :D

Don't worry about the title- no harm no foul! I renamed it so that it might be easier to find for others searching for a similar answer.

Issue closed!
