### ISSUE TITLE
Does it support raspberry's Gpu ??

### ISSUE THREAD

**Issue by Mouss94** [samjabrahams/tensorflow-on-raspberry-pi#3]
Hello , i would like to ask you please if the GPU in the raspberry is used by your Tensorflow wheel file ??
Thank you very much !!

**Comment by samjabrahams** [comment]
Thanks for the question: unfortunately it does not, at this time. TensorFlow's GPU implementation is designed to work with CUDA, CuDNN, etc, which is not supported by the Raspberry Pi.

It would be an incredible effort, but perhaps one day I (or someone, or a group of people) could attempt to do some work related to this. It would involve reimplementing all GPU operations to be done efficiently on the Raspberry Pi and then hooking those operations into TensorFlow's codebase.

For fun reference and coincidence, here's a [post from 2014 on Raspberry Pi GPU optimization by Pete Warden](http://petewarden.com/2014/08/07/how-to-optimize-raspberry-pi-code-using-its-gpu/), who is actually one of the Google members working on TensorFlow.
