### ISSUE TITLE
Trained NN not working on Raspberry Pi

### ISSUE THREAD

**Issue by zxzhijia** [samjabrahams/tensorflow-on-raspberry-pi#30]
### Describe the Issue
I trained a .pb and .txt on my laptop with 95% test accuracy. I also tested several images and get the correct output. But when I copy the .pb and .txt file to my raspberry pi and run classify.py. The output is completely wrong when given the same image, which is tested on my laptop correctly. In other words, the accuracy on raspberry pi is less than 30%(kind of like random pick). 

### Steps to Reproduce
Trained network on a different machine and load the .pb file and .txt file on raspberry pi to classify.

### Hardware/Software Info
laptop: ubuntu
installed tensorflow: 0.9.0rc0 linux x64

Please provide the following information about your Raspberry Pi setup:

* Raspberry Pi model: model 3 
* Operating System used: raspbian
* Version of Python used: python 2.7
* SD card memory size: 32
* Size of USB/other device used as swap (if building from source): 
* TensorFlow git commit hash (if building from source): 

### Relevant Console Output/Logs

**Comment by zxzhijia** [comment]
is it because the tensorflow on my laptop is 64bits while it's 32 bits on raspberry pi?

**Comment by samjabrahams** [comment]
Did you mean to close this up? Sorry for not getting back to you sooner- busy weekend.

**Comment by zxzhijia** [comment]
Yes, I closed it. No problem.
