### ISSUE TITLE
Tutorial Code fails on Pi3

### ISSUE THREAD

**Issue by SuperJonotron** [samjabrahams/tensorflow-on-raspberry-pi#31]
Attempting to run the code from the tutorial on tensorflow.org found here:
https://www.tensorflow.org/versions/r0.9/tutorials/tflearn/index.html

At the line:
classifier.fit(x=x_train, y=y_train, steps=200)

I get the error:
TypeError: DataType int64 for attr 'T' not in list of allowed values: float32, int32, qint8, quint8, qint32

I am running on a Pi3 on Raspbian GNU/Linux 8 (jessie)" with Python version 2.7.9

**Comment by samjabrahams** [comment]
Thanks for opening this up @SuperJonotron! I was able to replicate this bug, and this has been really helpful in pinpointing some quirks that were introduced in the official TensorFlow repository. I'm compiling now to see if I've got the fix hammered out.

If you're interested in the details (at least what I'm pretty sure is going on): Essentially, [these lines](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/platform.h#L40-L45) are causing the compilation to target the Raspberry Pi as a mobile device, which in turn causes no 64-bit floating points to be registered for any Ops [in this file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/register_types.h#L107-L131). The current hack-y fix is to delete [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/platform.h#L45). If that works, I'll try to get a fix introduced into the official repository that is a bit more robust.

I'll keep you posted on this.

**Comment by SuperJonotron** [comment]
Not sure if you've had a chance to try out the "hack-y fix" but I just commented out that line but still receive the same error.

I found the file at "/usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/platoform".  

If there is a different location where this file exists to try this change, let me know and I will try that too.

**Comment by samjabrahams** [comment]
In order to have the change take effect, the binaries have to be recompiled from scratch. I've done that and got the Iris program to work. Still need to test it more thoroughly, but I've updated the Python 2.7 binaries in the bin folder- try reinstalling it on your RPi and see if it works:

https://github.com/samjabrahams/tensorflow-on-raspberry-pi/raw/master/bin/tensorflow-0.9.0-cp27-none-linux_armv7l.whl

**Comment by SuperJonotron** [comment]
Few extra warnings that show up when running it now that weren't there before but they appear to be just warnings.  Error is gone and the code now completes.  

Thanks.

**Comment by samjabrahams** [comment]
If it's these warnings, they occur on all systems:

```
WARNING:tensorflow:Change warning: `feature_columns` will be required after 2016-08-01.
Instructions for updating:
Pass `tf.contrib.learn.infer_real_valued_columns_from_input(x)` or `tf.contrib.learn.infer_real_valued_columns_from_input_fn(input_fn)` as `feature_columns`, where `x` or `input_fn` is your argument to `fit`, `evaluate`, or `predict`.
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpeJinXa
WARNING:tensorflow:Setting feature info to TensorSignature(dtype=tf.float32, shape=TensorShape([Dimension(None), Dimension(4)]), is_sparse=False)
WARNING:tensorflow:Setting targets info to TensorSignature(dtype=tf.int64, shape=TensorShape([Dimension(None)]), is_sparse=False)
WARNING:tensorflow:Given features: Tensor("input:0", shape=(?, 4), dtype=float32), required signatures: TensorSignature(dtype=tf.float32, shape=TensorShape([Dimension(None), Dimension(4)]), is_sparse=False).
WARNING:tensorflow:Given targets: Tensor("output:0", shape=(?,), dtype=int64), required signatures: TensorSignature(dtype=tf.int64, shape=TensorShape([Dimension(None)]), is_sparse=False).
```

Glad it's working for you!
