### ISSUE TITLE
RPI3 compile w/ 0.10.RC0

### ISSUE THREAD

**Issue by AlexanderLitz** [samjabrahams/tensorflow-on-raspberry-pi#37]
Success.

A few things here - from a fresh Raspberry Pi3 install, you also need to install git, as well as the java JDK (I used Oracle)

You also need to change the Bazel minimum version in WORKSPACE under the main directory to:

check_version("0.2.0") 

to get it to build.  Not certain what happens when you don't revert to the version mentioned in the instructions.   Could still work.

Also, I did turn on the flag to compile with 2 cores on the RPI3, and it worked fine.   Again, not certain what the difference is in terms of compile time.

On graph accuracy, which some folks have complained about - when I used the release wheel (0.9.0) I was running into accuracy issues with graphs built w/ 0.10.0(basically, it didnt work at all), but after the native compile, the results between x64 Linux and RPI3 were identical.   

I wonder why noone just releases the RPI wheel...would make things much easier.

Happy inferencing.

**Comment by samjabrahams** [comment]
Thanks for the extra things to look out for. I'll do a fresh install of Raspbian to make sure that dependency installation information is accurate. Whenever I update the wheels, I also update the build instructions. 

I do release the RPi wheels, but I'm waiting for the official 0.10 release instead of just the release candidate. There were significant differences between 0.9RC0 and 0.9 in terms of installation, so I figure it makes sense to wait until the release goes gold.

**Comment by samjabrahams** [comment]
Just to keep progress: there are a couple bumps in the road that are causing a delay for the release of the next binary. TensorFlow 0.10 requires Bazel >= 0.3, which itself requires gRPC-java to be built from scratch on the RPi. 

* gRPC compile progress is here: #39
* [Bazel issue thread about this](https://github.com/bazelbuild/bazel/issues/1705)

**Comment by samjabrahams** [comment]
Hi @AlexanderLitz - 

Just wanted to point you to a [preliminary 0.10 binary](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/r0.10/bin/tensorflow-0.10.0-cp27-none-linux_armv7l.whl) for Python 2.7. I'm still toying around with the build and trying out some new optimizations, so this might just be a stopgap binary for the next day or two/three, but I figure it's better than nothing.

**Comment by samjabrahams** [comment]
[Version 0.10 binaries have been released](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases).
