### ISSUE TITLE
/configure --prefix=/usr install issue

### ISSUE THREAD

**Issue by Tondy** [samjabrahams/tensorflow-on-raspberry-pi#45]
### Describe the Issue

Hello as I am trying to go through the installation process when I get to this part.

/configure --prefix=/usr  > I get this current error >  ./configure --prefix=/usr
### Steps to Reproduce

./configure --prefix=/usr

bash: ./configure: No such file or directory
### Hardware/Software Info

Please provide the following information about your Raspberry Pi setup:
- Raspberry Pi model: P3
- Operating System used: 
- Version of Python used: 2.7 
- SD card memory size: 32
- Size of USB/other device used as swap (if building from source): 
- TensorFlow git commit hash (if building from source):

**Comment by samjabrahams** [comment]
Thanks for opening this up. Looks like the Protobuf folks changed their configuration setup. That said, you don't need to build `protobuf` from head at this time. Try checking out the recommended hash (`d5fb408d`) to follow the instructions as written. Alternatively, wait a few days and I should have updated instructions for building TensorFlow 0.10/0.11 (finally made some progress on building the newer versions of Bazel).

**Comment by neuralearner** [comment]
Thanks sam. Looking forward to the 0.10/0.11! Great work.

**Comment by Tondy** [comment]
Ok. Thanks will wait a few day. 

Cheers.

**Comment by neuralearner** [comment]
Hi sam, just wondering if you were still planning on updating to 0.10, I'm eagerly awaiting and so are my two Pis.

**Comment by neuralearner** [comment]
Hi sam, didn't see your previous comment here: https://github.com/samjabrahams/tensorflow-on-raspberry-pi/issues/44

will give it a try tomorrow.

**Comment by samjabrahams** [comment]
Hey @neuralearner - I just put out release binaries on the [releases page](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases). Let me know how everything works for you.

**Comment by samjabrahams** [comment]
[TensorFlow 0.12.1 binaries are now available, and the guide is updated.](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/tag/v0.12.1) This issue should be fixed.
