### ISSUE TITLE
com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension 'tensorflow/tensorflow.bzl' has errors.

### ISSUE THREAD

**Issue by neuralearner** [samjabrahams/tensorflow-on-raspberry-pi#46]
### Describe the Issue

Getting an error right before trying to compile tensorflow. Did some searching around and people have suggested that upgrading to bazel 0.3.1 seems to fix the issue but compiling for 0.3.1 has issues itself in raspberry pi but sam says a fix is coming in a few days:

https://github.com/samjabrahams/tensorflow-on-raspberry-pi/issues/44

### Steps to Reproduce
Follow all steps until ./configure

### Hardware/Software Info
Raspberry Pi + 16GB Swap

Please provide the following information about your Raspberry Pi setup:

* Raspberry Pi model: Raspberry Pi 3 Model B
* Operating System used:  Raspbian 8.0
* Version of Python used: 2.7.1
* SD card memory size: 32GB + 16GB Swap USB
* Size of USB/other device used as swap (if building from source): 
* TensorFlow git commit hash (if building from source): Latest as of today

### Relevant Console Output/Logs

ERROR: /home/pi/tf/tensorflow/tensorflow/tensorflow.bzl:636:21: syntax error at '=': expected expression.
ERROR: /home/pi/tf/tensorflow/tensorflow/tensorflow.bzl:711:1: nested functions are not allowed. Move the function to top-level.
ERROR: /home/pi/tf/tensorflow/tensorflow/tensorflow.bzl:739:1: nested functions are not allowed. Move the function to top-level.
ERROR: /home/pi/tf/tensorflow/tensorflow/tensorflow.bzl:773:1: nested functions are not allowed. Move the function to top-level.
ERROR: /home/pi/tf/tensorflow/tensorflow/tensorflow.bzl:776:1: nested functions are not allowed. Move the function to top-level.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension 'tensorflow/tensorflow.bzl' has errors.

**Comment by JamesRaynor67** [comment]
Try to upgrade your bazel to the latest, e.g. 0.3.1

**Comment by samjabrahams** [comment]
[TensorFlow 0.12.1 binaries are now available, and the guide is updated.](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/tag/v0.12.1) This includes instructions for Bazel 0.4.3, so hopefully this issue is now fine.
