### ISSUE TITLE
run() got an unexpected keyword argument 'argv'

### ISSUE THREAD

**Issue by AdamMiltonBarker** [samjabrahams/tensorflow-on-raspberry-pi#47]
### Describe the Issue

Hi guys. Having installed on an RPI3 using PIP, I have copied the code from:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/image/imagenet/classify_image.py

As could not find tensorflow directory, on executing:

`python tfimage.py` 

I get the error below. 

### Hardware/Software Info

Please provide the following information about your Raspberry Pi setup:

* Raspberry Pi model: 3
* Operating System used: Jessie
* Version of Python used: 2.7
* SD card memory size: 16gb
* Size of USB/other device used as swap (if building from source): NA
* TensorFlow git commit hash (if building from source): NA 

### Relevant Console Output/Logs

Traceback (most recent call last):
  File "tfimage.py", line 218, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
TypeError: run() got an unexpected keyword argument 'argv'

**Comment by samjabrahams** [comment]
Hi @AdamMiltonBarker , thanks for opening this up. I don't think this is an issue with Raspberry Pi specifically. It looks like this file was [recently changed](https://github.com/tensorflow/tensorflow/commit/6812d46b957e32eba37c67384cc2136908d7a1ff), which may be causing the issues. I'd check to see if the code works correctly on a desktop computer, and if it doesn't, open up an issue on the official TensorFlow repo.

**Comment by AdamMiltonBarker** [comment]
OK thanks will do, I have an idea I am working on also but the full details are confidential at this moment I would like your advice on something would it be possible to have a discussion privately via email please.

**Comment by AdamMiltonBarker** [comment]
Update to this I located the tensorflow folder and it is working from there or seems to be so far anyway, for anyone else that has issues finding the location it is here:

/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/imagenet
