### ISSUE TITLE
Tensorflow 0.10 build fail from gradle compilation

### ISSUE THREAD

**Issue by neuralearner** [samjabrahams/tensorflow-on-raspberry-pi#49]
Hi Sam,  I wanted to build from source and I"m getting this error while building the gradle:

FAILURE: Build failed with an exception.

* Where:
Build file '/home/pi/tf/grpc-java/all/build.gradle' line: 29

* What went wrong:
A problem occurred evaluating project ':grpc-all'.
> A problem occurred configuring project ':grpc-benchmarks'.
   > Could not resolve all dependencies for configuration ':grpc-benchmarks:protobufToolsLocator_protoc'.
      > Could not find protoc-linux-arm_32.exe (com.google.protobuf:protoc:3.0.0-beta-2).
        Searched in the following locations:
            https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.0.0-beta-2/protoc-3.0.0-beta-2-linux-arm_32.exe

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by cysheen** [comment]
happend to same error
how can i fix this error?

thanks

**Comment by samjabrahams** [comment]
@cysheen the guide needs a large overhaul due to new versions of protoc, Bazel and gRPC. I'm unable to work on this for two weeks, as I'm traveling abroad. If someone manages to find the secret sauce, hopefully they will share here, otherwise I'll get back to it when I am back at a computer.

**Comment by oprabhu** [comment]
looking forward to the fix.

**Comment by samjabrahams** [comment]
Just to give folks an update: I've successfully compiled Bazel 0.4.3 (the most recent version) on RPi, and am currently working through the TensorFlow build process. There were a few modifications to external libraries (namely the compiler flags for [gemmlowp](https://github.com/google/gemmlowp)) which were causing errors. Hopefully will start getting versions 0.12 and 1.0.0-alpha pushed (along with an updated guide) this weekend.

**Comment by samjabrahams** [comment]
[TensorFlow 0.12.1 binaries are now available, and the guide is updated.](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/tag/v0.12.1) This shouldn't be an issue anymore.
