### ISSUE TITLE
initialization of _pywrap_tensorflow raised unreported exception

### ISSUE THREAD

**Issue by tarpista** [samjabrahams/tensorflow-on-raspberry-pi#50]
Hello,
It looks that I could successfully install tensorflow on a raspberry pi...

**`pi@raspi:~ $ sudo pip3 install tensorflow-0.10.0-py3-none-any.whl`**

Unpacking ./tensorflow-0.10.0-py3-none-any.whl
Downloading/unpacking six>=1.10.0 (from tensorflow==0.10.0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking wheel>=0.26 (from tensorflow==0.10.0)
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB): 66kB downloaded
Downloading/unpacking protobuf==3.0.0b2 (from tensorflow==0.10.0)
  Downloading protobuf-3.0.0b2-py2.py3-none-any.whl (326kB): 326kB downloaded
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.2 in /usr/lib/python3/dist-packages (from tensorflow==0.10.0)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python3/dist-packages (from protobuf==3.0.0b2->tensorflow==0.10.0)
Installing collected packages: tensorflow, six, wheel, protobuf
  Found existing installation: six 1.8.0
    Not uninstalling six at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: wheel 0.24.0
    Not uninstalling wheel at /usr/lib/python3/dist-packages, owned by OS
Successfully installed tensorflow six wheel protobuf
Cleaning up...

...but when I run python3 and try to run...

**`import tensorflow`**

...it raises the following error:

RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
SystemError: initialization of _pywrap_tensorflow raised unreported exception

Here is my raspberry info:

**pi@raspi:~ $ cat /proc/cpuinfo**
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2709
Revision        : a02082
Serial          : 00000000d3397c5e

**pi@raspi:~ $ uname -a**
Linux raspi 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux

**pi@raspi:~ $ cat /etc/os-release**
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Thanks for any help!

**Comment by samjabrahams** [comment]
Hi @tarpista, thanks for opening this up. It looks like the version of NumPy on your Pi needs to be updated (not sure why the Python wheel doesn't upgrade this automatically). Try running this command and reinstall the TensorFlow pip package:

```
sudo pip3 install --upgrade numpy
```

**Comment by tarpista** [comment]
Hello Sam,
Thank you, that solved the problem! ;)
