### ISSUE TITLE
Tensorflow v0.11 is out, time to upgrade the wheel file

### ISSUE THREAD

**Issue by FlorinAndrei** [samjabrahams/tensorflow-on-raspberry-pi#52]
Trained a DNN on Ubuntu x86_64 using TensorFlow 0.11, moved the trained network on the RPi and tried to run it with 0.10, it gives nonsense results. I'm guessing this is due to differences between 0.11 and 0.10.

Tried to compile 0.11 on the RPi, but things have changed a little meanwhile, and the guide doesn't work so well anymore, I got a series of errors where there should have been none. I'll keep trying this weekend if I have time. I'll upload the wheel somewhere if I succeed.

Anyway, it's time for a general update to 0.11.

**Comment by samjabrahams** [comment]
Hey @FlorinAndrei - Thanks for the note; I missed that the last release candidate went gold. I setup a build of TensorFlow before I left for my Thanksgiving holiday. I'll try to get things up-to-date when I get back next week (this goes for the other issues you opened up a few days ago; apologies for not responding sooner)

**Comment by jtoy** [comment]
+1

**Comment by FlorinAndrei** [comment]
v0.12 is out, I made a new issue https://github.com/samjabrahams/tensorflow-on-raspberry-pi/issues/55

**Comment by samjabrahams** [comment]
Still going to be building these wheels, as 0.12.0 hasn't gone gold yet (still in release candidate stage)

**Comment by samjabrahams** [comment]
[TensorFlow 0.11.0 binaries are available on the releases page](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/tag/v0.11.0)
