### ISSUE TITLE
'--prefix=/usr' is not needed when configuring protobuf

### ISSUE THREAD

**Issue by FlorinAndrei** [samjabrahams/tensorflow-on-raspberry-pi#53]
`--prefix=/usr` will mix these files with files managed by apt/dpkg. And it's not needed, really.

Just run `./configure` without any options. Then `make install` will install in `/usr/local`. And then do `sudo ldconfig` and everything will be fine - the new libraries will be used by other apps.

**Comment by samjabrahams** [comment]
Which files are you concerned might interfere with something managed by a package manager? I'm inclined to keep this build step as-is, as it matches the "hint" provided on the [protobuf compilation README](https://github.com/google/protobuf/blob/master/src/README.md) (see the section labeled "Hint on install location"). 
 
I understand the desire to keep things organized "correctly", but this change wouldn't simplify anything (if anything, it adds an additional command to run). If there's no real risk to things getting screwed up, I'd prefer to keep it consistent with the protobuf repository.

**Comment by FlorinAndrei** [comment]
I don't think there is any conflict *right now*.

This is the kind of thing that seems like a non-issue until you get burned by it a couple times 😄 . I had that happen to me in the past. My current rule is: if the software seems to implement prefixes in `configure` correctly, then change the prefix to `/usr/local` and run `ldconfig`; if the software is broken, leave it alone and take your chances. Protobuf seems to be using `configure` correctly, so it falls in the first category.

Another thing to keep in mind is that cleaning up the mess, if need be, is a lot easier if you install in `/usr/local`.

Anyway, as long as no actual conflict happens, then any prefix is fine, of course.

**Comment by samjabrahams** [comment]
Fiiiiiine, you've convinced me :P 

Package/binary management isn't my area of expertise; I'm assuming that if you're passionate about this, you probably have more experience with the sort of issues people can run into.

I'm still working out the kinks updating the GUIDE, but I'll include this change in the new instructions. Once that's done I'll close this issue.

Thanks!

**Comment by samjabrahams** [comment]
[The guide has been updated](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/tag/v0.12.1), and we now put `protoc` in `/usr/local/bin`!
