### ISSUE TITLE
GPU enabled tensorflow version

### ISSUE THREAD

**Issue by tusharsoni08** [samjabrahams/tensorflow-on-raspberry-pi#56]
I'm using this repo's tensorflow version for my Jetson TK1(ARM) as Keras backend, I've Installed it with python2.7 using pip. It's working fine for me, but I think this version of tensorflow is for CPU, do you have GPU enabled support for it also. Thank you.

**Comment by samjabrahams** [comment]
Hi @tusharsoni08 - unfortunately I can't provide any direct assistance for the TK1, as I don't own one and can't step through and debug the process. That said, there was an [update to the original TK1 instructions](http://cudamusing.blogspot.com/2016/06/tensorflow-08-on-jetson-tk1.html) (which this repo was originally based on) showing how to compile an older version of TensorFlow (0.8), and you may be able to cross-reference it with the current instructions for RPi to step through the process yourself.

Good luck!

**Comment by tusharsoni08** [comment]
okay, but could you please let me about the GPU enabled support for RPi for tensorflow, since I think If that support RPi then It'll for TK1 also. Thank you!

**Comment by samjabrahams** [comment]
Unfortunately, I don't see GPU-enabled TensorFlow on the Raspberry Pi as a possibility in the short-to-medium term future. TensorFlow is starting to get OpenCL support, but the RPi doesn't have an OpenCL implementation. Maybe one day!
