### ISSUE TITLE
googlemock not present

### ISSUE THREAD

**Issue by indraneilmg** [samjabrahams/tensorflow-on-raspberry-pi#57]
Hello, I am trying to follow the steps to build tensorflow on an ARM board, I am trying to get the googlemock zip file & it does not exist

git checkout v3.0.0-beta-3.3
HEAD is now at bdeb215... Merge pull request #1737 from jcanizales/test

./autogen.sh
Google Mock not present.  Fetching gmock-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1582  100  1582    0     0   8789      0 --:--:-- --:--:-- --:--:--  8788
[gmock-1.7.0.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of gmock-1.7.0.zip or
        gmock-1.7.0.zip.zip, and cannot find gmock-1.7.0.zip.ZIP, period.

This is not a Pi but a different ARM board

**Comment by samjabrahams** [comment]
Thanks for opening this up @indraneilmg. I'm planning on stepping through the entire build process from a fresh install of Raspbian to make sure the dependencies and build steps are correct. Hopefully, fixes I make to the GUIDE for RPi will work for your own ARM board.

**Comment by samjabrahams** [comment]
While going through the GUIDE, I encountered your issue. You'll need to update `./autogen.sh` like the following diff:

https://github.com/google/protobuf/commit/bba446bbf2ac7b0b9923d4eb07d5acd0665a8cf0

**Comment by samjabrahams** [comment]
[The guide is updated](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/tag/v0.12.1), and this should no longer be an issue, as we checkout from `v3.0.0` instead of `v3.0.0-beta-3.3`.
