### ISSUE TITLE
I can`t install tensorflow properly

### ISSUE THREAD

**Issue by ulrichcha** [samjabrahams/tensorflow-on-raspberry-pi#58]
### Describe the Issue
pi@raspberrypi:~ $ sudo pip install tensorflow-0.11.0-cp27-none-linux_armv7l.whl
Unpacking ./tensorflow-0.11.0-cp27-none-linux_armv7l.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1365, in unpack_url
    unpack_file_url(link, location, download_dir)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 640, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 640, in unpack_file
    unzip_file(filename, location, flatten=not filename.endswith(('.pybundle', '.whl')))
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 510, in unzip_file
    zip = zipfile.ZipFile(zipfp)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file

Storing debug log for failure in /root/.pip/pip.log

I dont know why it doesnt work.... plz help me

### Hardware/Software Info
Please provide the following information about your Raspberry Pi setup:

* Raspberry Pi model: raspberry pi3 model b.
* Operating System used: mac
* Version of Python used: 2.7.9
* SD card memory size: 32GB
* Size of USB/other device used as swap (if building from source): 
* TensorFlow git commit hash (if building from source): 

### Relevant Console Output/Logs

**Comment by samjabrahams** [comment]
Interesting, the last time I saw this was in [this issue](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/issues/24), where the wrong thing was downloaded, though I don't think you would be able to make the same mistake (I changed how the files are hosted to prevent that from happening)

Just to get things going, how did you download the file? Did you use the `wget` command listed in the README?

```
$ wget https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/download/v0.11.0/tensorflow-0.11.0-cp27-none-linux_armv7l.whl
```

**Comment by ulrichcha** [comment]
I already did it for using wget.
But i searched about pip thingy. I cant fix it.

2016-12-09 4:42 GMT+09:00 Sam Abrahams <notifications@github.com>:

**Comment by samjabrahams** [comment]
Interesting. I managed to install the file properly on both of the Pis I tested it on. I'll give it another shot downloading from GitHub.

**Comment by ulrichcha** [comment]
Thank you very much!!!

**Comment by samjabrahams** [comment]
It looks like the installation is working fine on my end. There are two things I want to explore:

1. It's possible that your download got screwed up somehow. Try re-downloading it (maybe from the [releases page instead of using `wget`](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/tag/v0.11.0) and give it another shot.
2. If that doesn't work, I'll want to get more information about your operating system- I want to see if you're running the same version of Raspbian as I am (you listed Mac as your operating system above; I'm assuming you aren't running OSX on your RPi!). Run this command and let me know what it says:

```
$ cat /etc/*-release
```

**Comment by ulrichcha** [comment]
[image: 본문 이미지 1][image: 본문 이미지 2]

here it is... i downloaded that file again. After finishing download, same
problem appear

2016-12-08 23:25 GMT+01:00 Sam Abrahams <notifications@github.com>:

**Comment by samjabrahams** [comment]
Thanks. Can you copy/paste the output from `cat /etc/*-release`? The images you posted aren't showing up.

**Comment by ulrichcha** [comment]
Um.... This kinda error is coming now

**Comment by samjabrahams** [comment]
@ulrichcha What kind of error? Did you mean to post something in addition to your last comment?

**Comment by ulrichcha** [comment]
ahh when i past cat /etc/*-release, cat:/ /etc/*-release: No such file or directory, this messages showed up

**Comment by samjabrahams** [comment]
You're including the asterisk `*` character, right? `cat /etc/*-release` should work, `cat /etc/*-release` won't. Are you running Raspbian as your operating system on your RPi?

**Comment by ulrichcha** [comment]
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Opps sorry, i wrote wrong. here it is your requestion

**Comment by ulrichcha** [comment]
Finally, i can use your file. As what i did, i just dowunloaded it twice times... haha
Btw Thank you so much!!

**Comment by samjabrahams** [comment]
Alright- glad it eventually worked for you!
