### ISSUE TITLE
notimplemented: negative indices are currently unsupported

### ISSUE THREAD

**Issue by chaitanya2692** [samjabrahams/tensorflow-on-raspberry-pi#59]
The exact error is:-

File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 124, in _SliceHelper
    raise NotImplementedError("Negative indices are currently unsupported")
NotImplementedError: Negative indices are currently unsupported

Potential solutions (but not working):-
1) I have found a few issues but they say that they already fixed it on the latest versions. 
2) Running it in a tensorflow environment. (Can't find the tensorflow/bin/activate file)

Please help.

**Comment by samjabrahams** [comment]
@chaitanya2692 thanks for opening this up. Could you show me the portion of code that is causing this error? Additionally, could you verify that you're running TensorFlow 0.11.0 by running the following code:

```python
import tensorflow as tf
print(tf.__version__)
```

(As a side note, using a virtualenv environment shouldn't have an impact on how the code runs.)

**Comment by chaitanya2692** [comment]
I have been running version 0.9.0 as per the output of the code you have given me. 

The part of my code which was causing the problem was:- 
u_f = tf.reshape(u_1[-1], [1,])

Updating my version right now. Thanks a lot for the super fast response.
