### ISSUE TITLE
Bazel not found

### ISSUE THREAD

**Issue by AdamMiltonBarker** [samjabrahams/tensorflow-on-raspberry-pi#61]
### Describe the Issue

After installing by pip, bazel is not found when trying to run retrain.py Does bazel have to be installed in addition or is it a fault?

### Steps to Reproduce

Install with pip and execute:

`bazel build third_party/tensorflow/examples/image_retraining:retrain && \
bazel-bin/third_party/tensorflow/examples/image_retraining/retrain \
--image_dir ~/imagedir`

### Hardware/Software Info

Please provide the following information about your Raspberry Pi setup:

* Raspberry Pi model: 3
* Operating System used: Jessie
* Version of Python used: 2
* SD card memory size: 16gb
* Size of USB/other device used as swap (if building from source): 
* TensorFlow git commit hash (if building from source): 

### Relevant Console Output/Logs

-bash: bazel: command not found

**Comment by samjabrahams** [comment]
In order to use the `bazel` command to run the image retraining script, you'll need to build Bazel. That said, that particular Bazel command just runs [this Python file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py), more or less. Try running this command (assuming you're in the root TensorFlow directory) instead:

```shell
python tensorflow/examples/image_retraining/retrain.py --image_dir ~/imagedir
```

**Comment by samjabrahams** [comment]
Also, there's a chance that you run out of memory running this script: the Raspberry Pi isn't ideal for training models.

**Comment by AdamMiltonBarker** [comment]
Cool thank you for the quick reply. Will try soon. Just ran the classify_image_timed.py does it not respond with what the image has been classified with? I am sure I remembered it doing so before, maybe I am wrong though.

**Comment by AdamMiltonBarker** [comment]
Re the memory, we are just testing at the moment, if it is too much for the Pi, which we kind of guessed it would be will do a cloud based trainer and deploy to model to the device using MQTT.

**Comment by samjabrahams** [comment]
Yes, I updated it recently, as the primary motivation is to print out summary statistics. If you want to have that included again, you can copy/paste [this bit of code](https://github.com/tensorflow/models/blob/master/tutorials/image/imagenet/classify_image.py#L158-L167) back in at some point. You'll just have to be careful not to print it out on every iteration of the loop, or you'll get a mess of text on the console.

**Comment by AdamMiltonBarker** [comment]
OK cool thank you.

Re the initial issue:

The command you suggested gives the following:

`python: can't open file 'tensorflow/examples/image_retraining/retrain.py': [Errno 2] No such file or directory`

I also have the retrain script in the current working directory and get the following, which I remember from the first time I tried it. Will check out my other issue and see if I posted the solution:

`Traceback (most recent call last):
  File "trainInception.py", line 993, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
`

**Comment by samjabrahams** [comment]
I don't know what your present working directory is in bash; it's up to you to point python to [this file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py) in your cloned repo.

That traceback doesn't look complete. Did you copy/paste everything from the output?

**Comment by AdamMiltonBarker** [comment]
Sorry:

```
Traceback (most recent call last):
  File "trainInception.py", line 993, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
TypeError: run() got an unexpected keyword argument 'argv'
```

Also I had this issue before in a closed issue, and I can remember now solved it like that:

https://github.com/samjabrahams/tensorflow-on-raspberry-pi/issues/47

How it is at the moment I have a directory and inside that directory is retrain.py, BUILD and __init__.py Is not possible to rehome these files and execute in our own directory?

**Comment by AdamMiltonBarker** [comment]
I temporarily solved the above by reverting the change documented here:

https://github.com/tensorflow/tensorflow/commit/6812d46b957e32eba37c67384cc2136908d7a1ff#diff-e27def9997dcd569e1f2412fd6f3ae76

thanks for the quick help with this.

**Comment by AdamMiltonBarker** [comment]
@samjabrahams just an update on this I have successfully trained and identified myself on the RPI.
