### ISSUE TITLE
Can tensorflow c++ be used  on raspberry pi 3 with bazel 

### ISSUE THREAD

**Issue by Winphred** [samjabrahams/tensorflow-on-raspberry-pi#71]
right now i train model in python on desktop, output it and load the model with tensorflow c++ using bazel. everything is fine now. So, can I do it on RASPBEERY PI. and forget about trainning, I just use pi to execute my model in c.

**Comment by samjabrahams** [comment]
You should be able to build TensorFlow packages in Bazel on the Pi the same way you would on a desktop. However, if you want to load the model in C++, you might want to check out the [Makefile instructions on the official repo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile). There are some [examples of using them for the Pi](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/pi_examples), as well.
