### ISSUE TITLE
tensorflow-on-raspberry-pi: Cmd line for install .whl?

### ISSUE THREAD

**Issue by avantol** [samjabrahams/tensorflow-on-raspberry-pi#72]
Thanks for writing up the guide! 

I need some clarification on
sudo pip3 install <filename.whl>

I've read that using sudo is (vehemently) discouraged (IIRC, it messes with files it shouldn't)

I noticed that 
pip3 install --user <filename.whl>
which is the "recommended" form, causes permission errors.

Any comments on this?

Thanks!!!!

### Describe the Issue

n/a

### Steps to Reproduce

n/a

### Hardware/Software Info

Please provide the following information about your Raspberry Pi setup:

* Raspberry Pi model: 
3 mod B v1.2
* Operating System used: 
Stock Raspbian 8 Jessie from late 2016
* Version of Python used: 
3.4.2
* SD card memory size: 
16 GB
* Size of USB/other device used as swap (if building from source): 
n/a
* TensorFlow git commit hash (if building from source): 
n/a
### Relevant Console Output/Logs

**Comment by samjabrahams** [comment]
Not a bad suggestion- I'll try to update the instructions to be more secure. The main reasoning was that I wasn't _too_ worried about the risks of things getting screwy on the Pi. People are free to install it however they want, but it may be better to push people toward safer commands.

I'll try to work on this when I get a chance.

**Comment by samjabrahams** [comment]
`sudo pip install...` commands have been changed to `pip install --user...`
