### ISSUE TITLE
Error:zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by mohamed-sherif** [samjabrahams/tensorflow-on-raspberry-pi#76]
### Describe the Issue
Getting a Storing debug log for failure in /root/.pip/pip.log when attempting to install TensorFlow wheel for python 3
//sudo pip install tensorflow-1.0.0-cp27-none-linux_armv7

### Hardware/Software Info
Please provide the following information about your Raspberry Pi setup:

* Raspberry Pi model: rassberry pi3-modelB
* Operating System used: running Raspbian 8.0 ("Jessie")
* Version of Python used: python 3.4
* SD card memory size: 16GB
* Size of USB/other device used as swap (if building from source): non
* TensorFlow git commit hash (if building from source): 

### Relevant Console Output/Logs
Unpacking ./tensorflow-1.0.0-cp34-cp34m-linux_armv7l.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1365, in unpack_url
    unpack_file_url(link, location, download_dir)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 640, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 640, in unpack_file
    unzip_file(filename, location, flatten=not filename.endswith(('.pybundle', '.whl')))
  File "/usr/lib/python3/dist-packages/pip/util.py", line 510, in unzip_file
    zip = zipfile.ZipFile(zipfp)
  File "/usr/lib/python3.4/zipfile.py", line 937, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.4/zipfile.py", line 978, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Storing debug log for failure in /root/.pip/pip.log
#

**Comment by samjabrahams** [comment]
@mohamed-sherif - thanks for opening this up. Do you mind if I ask how you downloaded the file? Also, could you post the full `pip3 install ...` command that you used when you saw this error? Under "Describe the issue", you listed `sudo pip install tensorflow-1.0.0-cp27-none-linux_armv7`, which is the Python 2.7 file, but your console describes installing the Python 3.4 wheel.

**Comment by mohamed-sherif** [comment]
i have followed your steps:
### first i downloaded the file 
wget https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/download/v1.0.0/tensorflow-1.0.0-cp34-cp34m-linux_armv7l.whl

### then,i installed the file using pip
sudo pip3 install tensorflow-1.0.0-cp34-cp34m-linux_armv7l.whl

**Comment by samjabrahams** [comment]
Great, thanks. I'll attempt to reproduce the bug when I find some spare time near a Pi.

**Comment by mohamed-sherif** [comment]
@samjabrahams thank you so much :D .i think it was a server problem as **Error:zipfile.BadZipFile: File is not a zip file** was due to a corrupted .whl file, i have re-downloaded the file and the `sudo pip3 install tensorflow-1.0.0-cp34-cp34m-linux_armv7l.whl` command worked.thank you again for your time and consideration

**Comment by samjabrahams** [comment]
@mohamed-sherif glad to hear it!

**Comment by hungnv132** [comment]
I found the solution: https://stackoverflow.com/a/41916324/4436579

**Comment by Masquerade0097** [comment]
**[Solution]** 

1. Download file from here https://github.com/python/cpython/
2. Select the branch as per your python version. (for eg, https://github.com/python/cpython/blob/3.6/Lib/zipfile.py)
3. Paste it in /usr/lib/python3.6/zipfile.py in your local machine.
