### ISSUE TITLE
TensorFlow 1.0.1

### ISSUE THREAD

**Issue by samjabrahams** [samjabrahams/tensorflow-on-raspberry-pi#78]
Official release posting:

https://github.com/tensorflow/tensorflow/releases/tag/v1.0.1

Todo for this release:

* Build from scratch on a fresh install of Raspbian Jessie. Make note of specific release version (#73)
* Change `sudo pip install` to `pip install --user` (#72)

**Comment by hipitt** [comment]
Thank you very much for your work, which is of great help to me. Now I want to use c++ to implement my code, can you  release the libtensorflow.so ? Thanks.

PS:I'm using (tensorflow/tools/ci_build/builds/libtensorflow.sh) on x86 platforms


@samjabrahams

**Comment by samjabrahams** [comment]
@hipitt This repository isn't concerned with building the `libtensorflow.so` C++ library. You're welcome to build it yourself by following the guide's instructions to install Bazel on your Pi and run the appropriate `bazel build` command from there :)

**Comment by samjabrahams** [comment]
[1.0.1 binaries are available here](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/tag/v1.0.1)
