### ISSUE TITLE
Configure Error during Tensorflow causes error during Pi3 build "java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@llvm"

### ISSUE THREAD

**Issue by jamiekiely** [samjabrahams/tensorflow-on-raspberry-pi#80]
### Describe the Issue
After building with Bazel 0.4.3 causes error during tensorflow configure
### Steps to Reproduce
Following instructions here: https://github.com/samjabrahams/tensorflow-on-raspberry-pi
### Hardware/Software Info
Raspberry Pi3 
Please provide the following information about your Raspberry Pi setup:

* Raspberry Pi model: Pi3
* Operating System used:  Raspbian 8
* Version of Python used: 3+
* SD card memory size: 16GB
* Size of USB/other device used as swap (if building from source): 16GB
* TensorFlow git commit hash (if building from source): 

### Relevant Console Output/Logs
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@llvm

**Comment by samjabrahams** [comment]
@jamiekiely - thanks for opening this up. Could you copy/paste the error you're seeing from Bazel? Just saying "it causes an error" doesn't provide much direction for fixing it.

**Comment by jamiekiely** [comment]
Please update the build guide for newbies to use bazel version 0.4.4 and not 0.4.3, there is an error further along in the build which stops things


"wget https://github.com/bazelbuild/bazel/releases/download/0.4.4/bazel-0.4.4-dist.zip
unzip -d bazel bazel-0.4.4-dist.zip"

**Comment by jamiekiely** [comment]
Let me reproduce error again for dump, googled a day ago and found old issue that was resolved by updating bazel to 0.4.4.

**Comment by jamiekiely** [comment]
Issue is closed here: https://github.com/tensorflow/tensorflow/issues/7048

Workaround from the ticket is to do:
sudo update-ca-certificates -f
or 
update to bazel version 0.4.4

**Comment by jamiekiely** [comment]
In bazel 0.4.4 updates also the modification is different line (line 112) for java heap.

  run "${JAVAC}" -classpath "${classpath}" -sourcepath "${sourcepath}" \
      -d "${output}/classes" -source "$JAVA_VERSION" -target "$JAVA_VERSION" \
      -encoding UTF-8 "@${paramfile}" -J-Xmx500M

**Comment by exelban** [comment]
Successfully configured with Bazel 0.4.5.

Raspberry Pi 3
Python 3.5
Raspbian 8

**Comment by samjabrahams** [comment]
The instructions have been updated to use Bazel 0.4.5.
