### ISSUE TITLE
tensorflow-1.0.0-cp34-cp34m-linux_armv7l.whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by codelast** [samjabrahams/tensorflow-on-raspberry-pi#81]
### Describe the Issue
Hi, samjabrahams, when I try to install the v1.0.0 Tensorflow through the python-wheel provided by you, I got a error message said:
tensorflow-1.0.0-cp34-cp34m-linux_armv7l.whl is not a supported wheel on this platform

And of course, I've checked that I used the right command to install it:
pip3 install tensorflow-1.0.0-cp34-cp34m-linux_armv7l.whl

Actually I have successfully installed the v0.10.0 Tensorflow through your python-wheel before, and Tensorflow works fine. After you provided the new version package, I just want to upgrade my Tensorflow version too, so I ran into the error mentioned above.
So, could you please give me some hints on how to solve this problem?
Appreciate so much if I could get some help from you, thank you.

### Hardware/Software Info
Below are the output of lscpu command on my RPi 3:
Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Model:                 4
Model name:            ARMv7 Processor rev 4 (v7l)
CPU max MHz:           1200.0000
CPU min MHz:           600.0000
BogoMIPS:              38.40
Flags:                 half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32

Please provide the following information about your Raspberry Pi setup:

* Raspberry Pi model: 3B
* Operating System used: Arch Linux ARM, I installed the ARMv7 ArchLinuxARM for RPi 2 on my RPi3
* Version of Python used: 3.6.0
* SD card memory size: 8GB

**Comment by samjabrahams** [comment]
Hi @codelast - thanks for opening this up. Unfortunately, the Python wheel on the repo isn't compatible with Python 3.5 or 3.6, so you will need to build TensorFlow from source. I won't be providing wheels targeted for 3.5+ until there are officially supported binaries for the Raspberry Pi (it's my understanding that users have to build the most recent versions of Python from source).

That said, this makes me notice that the README indicates that the binaries would work on any version above 3.3, so I need to fix that. I'll close this issue once it's fixed.

**Comment by codelast** [comment]
OK, thank you @samjabrahams
