### ISSUE TITLE
tensorflow-1.0.0-cp27-none-linux_armv7l.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by exelban** [samjabrahams/tensorflow-on-raspberry-pi#83]
### Describe the Issue
When I try to install the Tensorflow through the python-wheel provided by you, I got a error message said:
tensorflow-1.0.0-cp27-none-linux_armv7l.whl is not a supported wheel on this platform

### Steps to Reproduce
```
apt-get update
apt-get install python-pip python-dev
wget https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/download/v1.0.0/tensorflow-1.0.0-cp27-none-linux_armv7l.whl

sudo pip install tensorflow-1.0.0-cp27-none-linux_armv7l.whl
```
### Hardware/Software Info

Please provide the following information about your Raspberry Pi setup:

* Raspberry Pi model: Raspberry Pi 3
* Operating System used: Raspbian 8
* Version of Python used: 2.7.9
* SD card memory size: 16
* Size of USB/other device used as swap (if building from source): 
* TensorFlow git commit hash (if building from source): 

### Relevant Console Output/Logs
```
sudo pip install tensorflow-1.0.0-cp27-none-linux_armv7l.whl
tensorflow-1.0.0-cp27-none-linux_armv7l.whl is not a supported wheel on this platform.
```

**Comment by samjabrahams** [comment]
Could you run `sha256sum tensorflow-1.0.0-cp27-none-linux_armv7l.whl` and copy/paste the output here? I want to double check that the file was downloaded correctly.

**Comment by exelban** [comment]
`737ffd7f47ebde167446930bf6ab2e22f6c95bb150ef7e9b9b06bbab79531662  tensorflow-1.0.0-cp27-none-linux_armv7l.whl`

**Comment by samjabrahams** [comment]
Great, thanks. Could you also tell me the output of `pip --version`? It's possible the default version of `pip` is pointing to Python 3+.

**Comment by exelban** [comment]
Oh, thanks. It was problem with pip. Default version was 9.0.1 from python3.5. 
Maybe you know how to change default pip?

**Comment by samjabrahams** [comment]
You'd have to adjust the symlink for `pip` if you want to adjust the default. If you just want to get it installed, try either of these commands:

```
sudo pip2 install tensorflow-1.0.0-cp27-none-linux_armv7l.whl
# OR
sudo pip2.7 install tensorflow-1.0.0-cp27-none-linux_armv7l.whl
```

I'm not on a Pi right now, so forgive me if I goof up these commands- I'm unable to test them first at the moment.

**Comment by exelban** [comment]
Thank you, pip2.7 return `sudo: pip2.7: command not found`.
Pip2 works, but return same error, i will try to fix it.

**Comment by samjabrahams** [comment]
You might also be able to use `pip` directly as a module, as it looks like your default `python` points to 2.7:

```
sudo python -m pip install tensorflow-1.0.0-cp27-none-linux_armv7l.whl
```

**Comment by exelban** [comment]
Thank you for help.
I have some problem with compiling tensorflow with python3.5.
Bazel was compiled successfully.
I was started compiling tensorflow in monday, but it only 1678 was compiled from 2k+ for today. It must take soo much time, or it's some problem with compiling tensorflow?

**Comment by samjabrahams** [comment]
Usually it takes less than a day for me to finish compiling, but it does take a _really really_ long time. If it's still going, I'd just let it sit.

**Comment by exelban** [comment]
Hm, it looks like i have some problem with bazel.
Maybe you have compiled tensorflow for python3.5?
