### ISSUE TITLE
'tensorboard' command not found after installation on RPI3

### ISSUE THREAD

**Issue by phil123456** [samjabrahams/tensorflow-on-raspberry-pi#87]
Bug in installation (tensorflow python code runs fine)

here are the step I used to install TensorFlow :

```
sudo apt-get install python-pip python-dev
wget https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/download/v1.0.1/tensorflow-1.0.1-cp27-none-linux_armv7l.whl
pip install --user tensorflow-1.0.1-cp27-none-linux_armv7l.whl
pip uninstall mock
pip install --user mock
sudo pip install --user git+https://github.com/tflearn/tflearn.git
```
the machine is a raspberrry pi v3 (raspbian v 8.0)
tensorflow v 1.0.1

problem :

I try to run tensorboard, I get a command not found

I tried locate, find, whereis, .... nothing, seems like it did not get installed with tensorflow

logs :

dont know if there are any install logs, if yes let me know where to find them

**Comment by phil123456** [comment]
I removed --user and it works, dont know why your tutorial insists on installing everything as non root while the default pi user needs to sudo everything anyway

pip install tensorflow-1.0.1-cp27-none-linux_armv7l.whl

**Comment by samjabrahams** [comment]
Hi @phil123456 - thanks for opening this up. Interesting- I wasn't aware that the `tensorboard` command wasn't installed properly when using the `--user` flag. I appreciate you following up with how you managed to fix the problem. I'll need to look into how to encourage a safe installation of the package while simultaneously making sure that the full functionality is available (such as `tensorboard`) and not having too many extra steps (I don't want to have a guide on creating a virtualenv in this repo).

For reference as to why the guide recommends using the `--user` flag in general, check out some of the following resources:

* http://stackoverflow.com/questions/15028648/is-it-acceptable-safe-to-run-pip-install-under-sudo
* http://stackoverflow.com/questions/21055859/what-are-the-risks-of-running-sudo-pip
* http://askubuntu.com/questions/802544/is-sudo-pip-install-still-a-broken-practice
* This change was originally brought up (with a user arguing _for_ this change) in #72

**Comment by samjabrahams** [comment]
I've reverted the `--user` flag instructions in the meantime as I investigate a better/working way to encourage "safe" `pip` practices.

**Comment by DanlanChen** [comment]
it is a sad story I need to do tensorflow --user because I do not have root right
