### ISSUE TITLE
autogen.sh script has some problem.

### ISSUE THREAD

**Issue by TaylorHere** [samjabrahams/tensorflow-on-raspberry-pi#9]
pi@raspberrypi:~/tf/protobuf $ ./autogen.sh
+ autoreconf -f -i -Wall,no-obsolete
./autogen.sh: 43: ./autogen.sh: autoreconf: not found

**Comment by TaylorHere** [comment]
It can easy to handle by sudo apt-get install automake

**Comment by TaylorHere** [comment]
In China，we can use google,so I fix the URL 123.57.232.144/gmock-1.7.0.zip

**Comment by samjabrahams** [comment]
Very interesting- was it two issues then? The first would be automake not being installed, and the second being the China-specific gmock download?

**Comment by samjabrahams** [comment]
Also, the tutorial already mentions installing `automake` in [this section](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md#1-install-basic-dependencies) - see the "For Protobuf" part.

**Comment by samjabrahams** [comment]
Pretty sure this is resolved by this point. Closing.
