### ISSUE TITLE
Broken installation with --user

### ISSUE THREAD

**Issue by dlime** [samjabrahams/tensorflow-on-raspberry-pi#91]
### Describe the Issue
Tensorflow will be installed to `/root/.local/lib/` instead of` /usr/local/lib` if `--user` is used
This will lead to import errors on my Rasperry PI 3.

In order to fix:
* Uninstalled all the packages in `/root/.local/lib/` (in order to list them do `sudo ls -l /root/.local/lib/python3.4/site-packages` ) also tensorflow by running `sudo pip3 uninstall <package-name>`)
* Install tensorflow without --user: `sudo pip3 install <tensorflow-arm7>.whl`

### Hardware/Software Info

* Raspberry Pi model: 3
* Operating System used: Raspian
* Version of Python used: 3.4
* SD card memory size: 64

### Relevant Console Output/Logs

Requirement already satisfied: tensorflow==1.0.1 from file:///home/pi/Deep-Learning-RC-Car-Data-Collector/tensorflow-1.0.1-cp34-cp34m-linux_armv7l.whl in /root/.local/lib/python3.4/site-packages

**Comment by samjabrahams** [comment]
Thanks for opening this up @dlime. Looks like the switch to using the `--user` flag has been [anything but smooth](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/issues/87). I'm going to switch instructions back to using `sudo` for the time being. It may just be easiest to instruct folks to use a virtualenv if they want to isolate their installations.
